**NumPy** - это фундаментальный пакет для научных вычислений на Python. 
Он содержит, помимо прочего: 
* мощный N-мерный массив объектов
* полезные элементы линейной алгебры написанные на языке C / C ++ и Фортран
* преобразования Фурье и случайные чисела. 

Помимо очевидного научного использования, NumPy также может использоваться как эффективный многомерный контейнер данных.

In [1]:
import numpy as np

## Массивы

Массив numpy представляет собой сетку значений одного типа и индексируется кортежем неотрицательных целых чисел. Число измерений-это ранг массива; форма массива - это кортеж целых чисел, дающих размер массива вдоль каждого измерения.

Мы можем инициализировать массивы numpy из стандартных списков Python и получить доступ к элементам с помощью квадратных скобок:

In [2]:
a = np.array([1, 2, 3])
print(type([1, 2, 3]))
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  

<class 'list'>
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


NumPy включает в себя множество функций для создания массивов:

In [4]:
a = np.zeros((2,2))
print(a)  

[[0. 0.]
 [0. 0.]]


In [5]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [6]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [7]:
d = np.eye(2)
print(d) 

[[1. 0.]
 [0. 1.]]


In [8]:
e = np.random.random((2,2))
print(e)

[[0.39802205 0.75259138]
 [0.51659467 0.22151622]]


Про все остальные способы создать массив можно прочитать в документации https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation

## Индексации массива 
Numpy предлагает несколько способов индексирования.

### Срезы:
так же как в списках в Python.
Поскольку массивы могут быть многомерными, необходимо указать срез для каждого измерения массива.

In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
b = a[:3, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 2  3]
 [ 6  7]
 [10 11]]


In [27]:
x = [1, 3, 23]
y = x[::1]
print(x, '\n')
x = [1, 5, 23]
print(y, '\n')
for elem in y:
    elem += 1
print(y, '\n')
print(x)

[1, 3, 23] 

[1, 3, 23] 

[1, 3, 23] 

[1, 5, 23]


Срез списка указывает на те же данные, изменяя срез мы изменим и исходный список

In [10]:
b[0, 0] = 123
print(a, '\n')
print(b)

[[  1 123   3   4]
 [  5   6   7   8]
 [  9  10  11  12]] 

[[123   3]
 [  6   7]]


### Целочисленное индексирование
При индексировании с помощью срезов резултат всегда будет подмассивом исходного. Целочисленное индексирование позволяет создавать произвольные массивы, используя данные из другого массива.

In [28]:
a = np.array([[1,2], [3, 4], [5, 6]])
b = a[[0, 1, 2], [0, 1, 0]]

print(a, a.shape, '\n')
print(b, b.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2) 

[1 4 5] (3,)


Пример выше эквивалентен такому:

In [29]:
b = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(b, b.shape)

[1 4 5] (3,)


Так же можно использовать один и тот же элемент несколько раз

In [30]:
print(a[[0, 0], [1, 1]])
# Пример выше эквивалентен такому:
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


Один полезный трюк с целочисленным индексированием массива -- выбор или изменеие одного элемента из каждой строки матрицы:

In [34]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a, '\n')

# Создадим массив индексов
b = np.array([0, 2, 0, 1])

# Выбирем один элемент из скаждой строки по индексам из b
print(a[np.arange(4), b], '\n')  

# Изменим эти элементы
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[ 1  6  7 11] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


 Можно также смешивать целочисленное индексирование со срезами.Это даст массив более низкого ранга, чем исходный массив. 

In [35]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 ссылается на вторую строчку a
row_r2 = a[1:2, :]  # Rank 2 ссылается на вторую строчку a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


Со столбцами всё точно так же

In [36]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) 
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Логическое индексирование
позволяет выбирать произвольные элементы массива. Часто этот тип индексирования используется для выбора элементов массива, удовлетворяющих некоторому условию. Вот пример:

In [37]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Возвращает массив Booleans такого же размера как a

print(bool_idx)


[[False False]
 [ True  True]
 [ True  True]]


Используем логическое индексирование массива чтобы построить массив
состоящий из элементов `a`, соответствующих истинным значениям из `bool_idx`

In [38]:
print(a[bool_idx])

[3 4 5 6]


Всё можно записать в одну строчку. Очень лаконично

In [39]:
print(a[a > 2]) 

[3 4 5 6]


Для краткости мы оставили много деталей об индексации массива numpy; если вы хотите узнать больше, вы должны прочитать документацию. https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

## Типы данных
Каждый массив numpy представляет собой сетку элементов одного типа. Numpy содержит большой набор числовых типов данных, которые можно использовать для создания массивов. Numpy пытается угадать тип данных при создании массива, но функции, которые строят массивы, обычно также включают необязательный аргумент для явного указания типа данных. Вот пример:

In [40]:
x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])   
print(x.dtype)

x = np.array([1, 2], dtype=np.float64)
print(x.dtype)                    

int64
float64
float64


В первых двух примерах тип данных выбрался автоматически. В третьем мы явно его указали.
Не будем подробно останавливаться на типах данных, если интересно вы можете прочитать подробнее в документации. https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

## Арифметика массивов
Основные математические функции работают поелементно в массивах и доступны как в качестве перегрузок операторов, так и в качестве функций в модуле numpy:

In [41]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

Поэлементная сумма, разность, умножение, деление и квадратный корень

In [42]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [43]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [44]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [45]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [46]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Обратите внимание, что `x * y` это поэлементное умножене, а не матричное произведение из линала. Если нужно матричное произведение, нужно использовать специальную функцию.

In [47]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

Скалярное произведение векторов

In [48]:
print(v.dot(w))
print(np.dot(v, w))

219
219


Умножение матрицы на вектор

In [49]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


Матричное умножение

In [50]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy предоставляет множество полезных функций для выполнения вычислений на массивах; одна из самых полезных-`sum`:

In [51]:
x = np.array([[1,2],[3,4]])

print(x, '\n')

print(np.sum(x))          # Сумма всех элементов
print(np.sum(x, axis=0))  # Сумма каждого столбца
print(np.sum(x, axis=1))  # Сумма каждой строки

[[1 2]
 [3 4]] 

10
[4 6]
[3 7]


Полный список математических функций можете посмотреть в документации
https://docs.scipy.org/doc/numpy/reference/routines.math.html

Помимо вычисления математических функций с использованием массивов, нам часто приходится изменять или иным образом манипулировать данными в массивах. Самый простой пример такого типа операции-транспонирование матрицы; чтобы транспонировать матрицу, просто используйте атрибут T объекта array:

In [52]:
x = np.array([[1,2], [3,4]])
print(x,'\n')
print(x.T)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


Транспонирование ветора ничего не делает

In [53]:
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


Numpy предоставляет гораздо больше функций для управления массивами; вы можете увидеть полный список в документации. https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

## Broadcasting
мощный механизм, позволяющий numpy работать с массивами различной формы при выполнении арифметических операций. Часто у нас есть меньший массив и больший массив, и мы хотим использовать меньший массив несколько раз для выполнения некоторой операции над большим массивом.

Например, предположим, что мы хотим добавить постоянный вектор к каждой строке матрицы. Мы можем сделать это так:

In [54]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Пустая (заполненная мусором) матрица той же размерности, что и x

# Для каждой строки матрицы x в цикле доболяем вектор v
for i in range(4):
    y[i, :] = x[i, :] + v

print(x, '\n')
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Это работает! 
Но, когда матрица `x` очень велика, вычисление цикла в Python может быть медленным. Обратите внимание, что добавление вектора v в каждую строку матрицы x эквивалентно формированию матрицы `vv` путем укладки нескольких копий v вертикально, а затем выполнения элементарного суммирования `x` и `vv`. Мы могли бы реализовать такой подход:

In [55]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Склеить 4 копии вектора v друг на друга
print(vv, '\n')                 

y = x + vv  # Сложение из numpy
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting позволяет нам выполнять это вычисление без фактического создания нескольких копий `v`.

In [56]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Строчка `y = x + v` работает несмотря на то, что `x.shape == (4, 3)` и `v.shape == (3,)`. Это работает как если бы  `v.shape`  было `(4,3)` где каждая строка была копией `v`, а сумма считается поэлементно.

Этот краткий обзор коснулся многих важных вещей, которые вы должны знать о numpy, но далек от завершения. По ссылке вы можете узнать много нового и полезного. https://docs.scipy.org/doc/numpy/reference/

## Зачем всё это?
Вы могли слышать, что один из минусов питона, это его большое время работы. NumPy пытается как-то решить эту проблему. Многие его функции реализованы на си или фортране. Рассмотрим пример

In [57]:
import time

size_of_vec = 30000

def python():
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - start

def numpy():
    start = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - start

print("Numpy is in this example {} times faster!".format(python()/numpy()))


Numpy is in this example 21.463294028147583 times faster!


### Упражнение 1
Постройте график ускорения получаемого с использованием массивов numpy по сравнению со списками в питоне от размера массива. 
Для более точных результатов замеряйте время выполнения функции несколько раз и усредняйте. (можно использовать модуль Timer из библиотеки timeit)
* Используйте функцию `z = 2*x**2 + 4*y`
* Перемножение матриц размера n на n

In [74]:
import matplotlib.pyplot as plt
for i in range(size_of_vec):
    def python():
        start = time.time()
        X = range(i)
        Y = range(i)
        Z = [2*X[i]**2 + 4*Y[i] for i in range(len(X)) ]
        return time.time() - start

    def numpy():
        start = time.time()
        X = np.arange(i)
        Y = np.arange(i)
        Z = 2*x**2 + 4*y
        return time.time() - start


x = np.arange(-10, 10.01, 0.01)
plt.plot(numpy(), python())

plt.show()

ValueError: operands could not be broadcast together with shapes (2001,) (4,3) 

In [2]:
import numpy as np
import matplotlib.pyplot as plt
t = np.arange(0, 2*np.pi, 0.01)
r = 4
plt.plot(r*np.sin(t), r*np.cos(t), lw=3)
plt.axis('equal')
plt.show()

<Figure size 640x480 with 1 Axes>

### Упражнение 2
* Создать массив чисел от 2 до 75. Вывести только нечётные. 
* Присвоить нечётным числам этого массива значение -1.


In [88]:
a = np.array(range(2, 75))
bool_idx = (a % 2 == 0)
print(a[bool_idx])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74]


### Упражнение 3
* прочитать про функцию reshape, запустить и понять все пимеры https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html?highlight=reshape#numpy.reshape
* Найти в документации функцию, которая удаляет из одного массива элементы, которые есть в другом. Вспомнить как то же самое проделать с множествами

In [75]:
a = np.arange(6).reshape((3, 2))

In [76]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
np.reshape(a, (2, 3)) # C-like index ordering


array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

In [81]:
np.reshape(a, (3, 2), order='F') # Fortran-like index ordering

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [83]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [84]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [85]:
np.reshape(a, (3,-1)) 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
index = [2, 3, 6]

new_a = np.delete(a, index)

print(new_a)

[1 2 5 6 8 9]


In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3,4,7])
c = np.setdiff1d(a,b)

In [5]:
c

array([1, 2, 5, 6, 8, 9])

### Упражнение 4

* Создать случаую квадратную матрицу случайного размера от 10 до 100. 
* Найти максимум и сумму элементов.
* Поделить каждый элемент на максимум.
* Отнять от каждой строки матрицы среднее по строке
* Заменить максимальное значение на -1.

In [20]:
import random as rnd 

n=rnd.randint(5,10) 

arr = np.zeros((n,n)) 

for i in range(n): 
    for j in range(n): 
        arr[i,j]=rnd.randint(1,100) 

print(arr) 


Создать случаую квадратную матрицу
[[99.  2.  7. 27. 94.]
 [ 3.  6. 19.  3. 25.]
 [27. 31. 92. 54. 14.]
 [90. 66. 23.  6. 28.]
 [69. 96. 27. 88. 19.]]
___________________________


In [7]:
sum=0 
max=arr[1,1] 
for i in range(n): 
    for j in range(n): 
        sum += arr[i,j] 
if arr[i, j] > max: 
    max = arr[i, j] 

print('Sum=',sum) 
print('Max=', max) 



Sum= 368778.0
Max= 58.0
__________________________


In [8]:
for i in range(n): 
    for j in range(n): 
        arr[i,j] = arr[i,j]/maximum 

print(arr) 


Поделить каждый элемент на максимум
[[0.43103448 0.63793103 1.4137931  ... 1.25862069 1.63793103 1.34482759]
 [1.63793103 0.13793103 1.12068966 ... 1.55172414 0.31034483 1.68965517]
 [1.15517241 1.18965517 0.03448276 ... 1.39655172 0.44827586 0.43103448]
 ...
 [1.         1.0862069  1.20689655 ... 0.15517241 1.51724138 0.56896552]
 [0.43103448 0.55172414 0.18965517 ... 1.39655172 0.20689655 1.25862069]
 [1.32758621 0.87931034 0.84482759 ... 0.15517241 1.22413793 1.        ]]
___________________________


In [16]:
S=0 
for i in range(n): 
    for j in range(n): 
        S += arr[i,j] 
for c in range(n): 
    arr[i,c] = arr[i,j]-S/n 
    
print(arr) 


Отнять от каждой строки матрицы среднее по строке
[[ 4.31034483e-01  6.37931034e-01  1.41379310e+00 ...  1.25862069e+00
   1.63793103e+00  1.34482759e+00]
 [ 1.63793103e+00  1.37931034e-01  1.12068966e+00 ...  1.55172414e+00
   3.10344828e-01  1.68965517e+00]
 [ 1.15517241e+00  1.18965517e+00  3.44827586e-02 ...  1.39655172e+00
   4.48275862e-01  4.31034483e-01]
 ...
 [ 1.00000000e+00  1.08620690e+00  1.20689655e+00 ...  1.55172414e-01
   1.51724138e+00  5.68965517e-01]
 [ 4.31034483e-01  5.51724138e-01  1.89655172e-01 ...  1.39655172e+00
   2.06896552e-01  1.25862069e+00]
 [-7.39436105e+01 -7.39436105e+01 -7.39436105e+01 ... -7.39436105e+01
  -7.39436105e+01 -7.39436105e+01]]
___________________________


In [21]:
maximum=0 
[a,b]=[0,0] 
for i in range(n): 
    for j in range(n): 
        if arr[i,j] > maximum: 
            maximum = arr[i,j] 
[a,b]=[i,j] 

arr[a,b] = -1 
print(arr)

Заменить максимальное значение на -1
[[99.  2.  7. 27. 94.]
 [ 3.  6. 19.  3. 25.]
 [27. 31. 92. 54. 14.]
 [90. 66. 23.  6. 28.]
 [69. 96. 27. 88. -1.]]


### Упражнение 5
* Научиться записывать наймпай массив в файл.
* Научиться читать массив из файла.

In [12]:
with open("arrays.txt", 'w+') as f:
    f.write(str(c))

In [13]:
arrays.txt

NameError: name 'arrays' is not defined

In [11]:
f = open('arrays.txt')

In [12]:
f.read()

'[1 2 5 6 8 9]'

### Упражнение 6
* Как в массиве найти ближайший элемент к данному? 

In [2]:
import numpy as np 
def find_nearest(array,value): 
    idx = (np.abs(array-value)).argmin() 
    return array[idx] 

array = np.random.random(10) 
print(array, '\n') 

value = 0.5 

print(find_nearest(array, value))

[0.04088562 0.24808479 0.15146908 0.90637331 0.45352273 0.43856155
 0.70882336 0.80090004 0.28249563 0.24843708] 

0.4535227269644978


### Упражнение*
* Напишите игру жизнь используя массивы нампай.
